// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDOaakQqPC2z3KBATy8R_PppKteO7AiNg',
    appId: '1:598309562855:web:b5bc3977df385225853542',
    messagingSenderId: '598309562855',
    projectId: 'asistenciasappcristiana',
    authDomain: 'asistenciasappcristiana.firebaseapp.com',
    storageBucket: 'asistenciasappcristiana.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAc61YTUCGPnjMxTGLNU66Lu1IsGyAE3E',
    appId: '1:598309562855:android:6327c5c1b67118e7853542',
    messagingSenderId: '598309562855',
    projectId: 'asistenciasappcristiana',
    storageBucket: 'asistenciasappcristiana.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxrNfBUKSrdXMiejtlxPN-Df3lLKSZta8',
    appId: '1:598309562855:ios:30636b97c3e85235853542',
    messagingSenderId: '598309562855',
    projectId: 'asistenciasappcristiana',
    storageBucket: 'asistenciasappcristiana.firebasestorage.app',
    iosBundleId: 'com.example.asistenciasApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxrNfBUKSrdXMiejtlxPN-Df3lLKSZta8',
    appId: '1:598309562855:ios:30636b97c3e85235853542',
    messagingSenderId: '598309562855',
    projectId: 'asistenciasappcristiana',
    storageBucket: 'asistenciasappcristiana.firebasestorage.app',
    iosBundleId: 'com.example.asistenciasApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBDOaakQqPC2z3KBATy8R_PppKteO7AiNg',
    appId: '1:598309562855:web:6edd74ab02e1f2c9853542',
    messagingSenderId: '598309562855',
    projectId: 'asistenciasappcristiana',
    authDomain: 'asistenciasappcristiana.firebaseapp.com',
    storageBucket: 'asistenciasappcristiana.firebasestorage.app',
  );
}
